/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bill;


import Login.Login;
import Login.Home;
import Login.User;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import java.sql.SQLException;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import pharmacy.pharmacy;
import pharminfo.pharminfo;

/**
 *
 * @author HP
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        
        }
            
        DisplayTable();
    }
 private void DisplayTable()
    { 
        
    
        
       try {
           String url = "jdbc:mysql://localhost:3306/pharmacy";
             Connection conn = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url,"root","Pharm@123");
            String sql= "select * from selll ";
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        }catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } }
 
 public void bill()
 {
     String tot = jtxtTot1.getText();
     String pay=jtxtPay.getText();
     String bal=jtxtBal.getText();
     DefaultTableModel model = new DefaultTableModel();
     model=(DefaultTableModel)jTable3.getModel();
     txtbill.setText(txtbill.getText()+"************************************************************************************************\n");
     txtbill.setText(txtbill.getText()+"                                              PHARMACY BILL                                     \n");
     txtbill.setText(txtbill.getText()+"************************************************************************************************\n");
     txtbill.setText(txtbill.getText()+"Medicine"+"\t"+"Price"+"\t"+"Quantity"+"\t"+"Amount"+"\n");
     for(int i=0;i<model.getRowCount();i++)
     {
         String mname=(String)model.getValueAt(i, 0);
         String mprice=(String)model.getValueAt(i, 4);
         String mqnt=(String)model.getValueAt(i, 3);
         String mamt=(String)model.getValueAt(i, 5);
         txtbill.setText(txtbill.getText()+mname+"\t"+ mprice+"\t"+mqnt+"\t"+mamt+"\n");
     }
     txtbill.setText(txtbill.getText()+"\n");
     
     txtbill.setText(txtbill.getText()+"\t"+"\t"+"\t"+"Subtotal:"+tot+"\n");
     txtbill.setText(txtbill.getText()+"\n");
     txtbill.setText(txtbill.getText()+"\t"+"\t"+"\t"+"Pay:"+pay+"\n");
     txtbill.setText(txtbill.getText()+"\n");
     txtbill.setText(txtbill.getText()+"\t"+"\t"+"\t"+"Balance:"+bal+"\n");
     txtbill.setText(txtbill.getText()+"\n");
     txtbill.setText(txtbill.getText()+"\n");
     txtbill.setText(txtbill.getText()+"************************************************************************************************\n");
     txtbill.setText(txtbill.getText()+"                             THANKYOU VISIT AGAIN!                                              \n");
     
     
         
         
         
     
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxtName1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtRef1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDose1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtExp1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtQnt1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtPrice1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtxtBal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtTot1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtPay = new javax.swing.JTextField();
        jbtnCal1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnUpdate1 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnPatient1 = new javax.swing.JButton();
        jbtnSearch = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnCal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Medicine Name:");

        jtxtName1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Medicine Code:");

        jtxtRef1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Dose:");

        jtxtDose1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Expiry Date:");

        jtxtExp1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Quantity:");

        jtxtQnt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtQnt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtQnt1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtxtQnt1MouseReleased(evt);
            }
        });
        jtxtQnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQnt1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Price :");

        jtxtPrice1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtRef1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jtxtDose1)
                    .addComponent(jtxtName1))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtExp1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jtxtQnt1)
                    .addComponent(jtxtPrice1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtExp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtRef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jtxtDose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jtxtQnt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Total Amount:");

        jtxtBal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtBal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxtBalMouseEntered(evt);
            }
        });
        jtxtBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Balance:");

        jtxtTot1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtTot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTot1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Payment:");

        jtxtPay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPayActionPerformed(evt);
            }
        });

        jbtnCal1.setText("PRINT BILL");
        jbtnCal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnCal1)
                    .addComponent(jtxtTot1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtTot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jbtnCal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnUpdate1.setText("ADD");
        jbtnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdate1ActionPerformed(evt);
            }
        });

        btnSave.setText("UPDATE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jbtnDoctor.setText("CANCEL");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });

        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnPatient1.setText("STOCK");
        jbtnPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatient1ActionPerformed(evt);
            }
        });

        jbtnSearch.setText("SEARCH");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jbtnLogin.setText("BACK");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnCal.setText("CALCULATE");
        jbtnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnUpdate1)
                .addGap(26, 26, 26)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(jbtnDoctor)
                .addGap(18, 18, 18)
                .addComponent(jbtnDelete)
                .addGap(18, 18, 18)
                .addComponent(jbtnPatient1)
                .addGap(18, 18, 18)
                .addComponent(jbtnSearch)
                .addGap(18, 18, 18)
                .addComponent(jbtnCal)
                .addGap(18, 18, 18)
                .addComponent(jbtnLogin)
                .addGap(18, 18, 18)
                .addComponent(jbtnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPatient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnCal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnExit)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Medicine Code", "Dose", "Expiry Date", "Quantity", "Price", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable3MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3);

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtQnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQnt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQnt1ActionPerformed

    private void jtxtBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBalActionPerformed

    }//GEN-LAST:event_jtxtBalActionPerformed

    private void jtxtTot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTot1ActionPerformed

    private void jtxtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPayActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int i= jTable3.getSelectedRow();
        TableModel res=jTable3.getModel();
        jtxtName1.setText(res.getValueAt(i,0).toString());
        jtxtRef1.setText(res.getValueAt(i,1).toString());
        jtxtDose1.setText(res.getValueAt(i,2).toString());
        jtxtExp1.setText(res.getValueAt(i,3).toString());
        jtxtQnt1.setText(res.getValueAt(i,4).toString());
        jtxtPrice1.setText(res.getValueAt(i,5).toString());
        jtxtTot1.setText(res.getValueAt(i,6).toString());

    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseEntered

    }//GEN-LAST:event_jTable3MouseEntered

    private void jbtnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdate1ActionPerformed
        DefaultTableModel model1= (DefaultTableModel)jTable3.getModel();

        model1.addRow(new Object[]{

            jtxtName1.getText(),
            jtxtRef1.getText(),
            jtxtDose1.getText(),
            jtxtExp1.getText(),
            jtxtQnt1.getText(),
            jtxtPrice1.getText(),
            jtxtTot1.getText(),
            
            

        });

    }//GEN-LAST:event_jbtnUpdate1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        String url = "jdbc:mysql://localhost:3306/pharmacy";
        Connection conn = null;

        try{

            conn = DriverManager.getConnection(url,"root","Pharm@123");
            System.out.println("connection successful");
            String sql = "insert into selll values(?,?,?,?,?,?,?)";
            PreparedStatement ps=conn.prepareStatement(sql);

            ps.setString(1,jtxtName1.getText());
            ps.setString(2,jtxtRef1.getText());
            ps.setString(3,jtxtDose1.getText());
            ps.setString(4,jtxtExp1.getText());
            ps.setString(5,jtxtQnt1.getText());

            ps.setString(6,jtxtPrice1.getText());
            ps.setString(7,jtxtTot1.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Saved");
            jtxtName1.setText("");
            jtxtRef1.setText("");
            jtxtDose1.setText("");
            jtxtQnt1.setText("");
            jtxtPrice1.setText("");
            jtxtExp1.setText("");
            jtxtTot1.setText("");
        }catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
        jtxtName1.setText("");
        jtxtRef1.setText("");
        jtxtDose1.setText("");
        jtxtQnt1.setText("");
        jtxtPrice1.setText("");
       
        jtxtExp1.setText("");
        jtxtTot1.setText("");
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        }catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        String url = "jdbc:mysql://localhost:3306/pharmacy";
        Connection conn = null;

        try{
            String bb=jtxtRef1.getText();
            conn = DriverManager.getConnection(url,"root","Pharm@123");

            PreparedStatement ps=conn.prepareStatement("Delete from selll where bb=?");
            ps.setString(1,bb);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Deleted");
            DisplayTable();
        }catch (SQLException ex)
        {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatient1ActionPerformed
        pharminfo ipharminfo = new pharminfo();
        ipharminfo.setVisible(true);
    }//GEN-LAST:event_jbtnPatient1ActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        String url = "jdbc:mysql://localhost:3306/pharmacy";
        Connection conn = null;

        try{

            conn = DriverManager.getConnection(url,"root","Pharm@123");
            System.out.println("connection successful");
            String sql = "select * from pharmm where Medicine_Name=? and Dose=?";
            PreparedStatement ps=conn.prepareStatement(sql);

            ps.setString(1,jtxtName1.getText());
            ps.setString(2,jtxtDose1.getText());

            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"MEDICINE AVAILABLE");
                jtxtName1.setText(rs.getString("Medicine_Name"));
                jtxtRef1.setText(rs.getString("Medicine_Code"));
                jtxtExp1.setText(rs.getString("Expiry_Date"));
                jtxtPrice1.setText(rs.getString("Price"));
            }
            else
            {
                JOptionPane.showMessageDialog(this,"MEDICINE NOT AVAILABLE");
            }

        }catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Pharmacy Management Systems",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0); }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalActionPerformed
        int qnt= Integer.parseInt(jtxtQnt1.getText());
        int prc= Integer.parseInt(jtxtPrice1.getText());
        int tot= qnt*prc;
        jtxtTot1.setText(String.valueOf(tot));
    }//GEN-LAST:event_jbtnCalActionPerformed

    private void jbtnCal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCal1ActionPerformed
         int tot =Integer.parseInt(jtxtTot1.getText());
        int pay = Integer.parseInt(jtxtPay.getText());
        int bal = pay - tot;
        jtxtBal.setText(String.valueOf(bal));
        bill();
    }//GEN-LAST:event_jbtnCal1ActionPerformed

    private void jtxtBalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBalMouseEntered
        int tot =Integer.parseInt(jtxtTot1.getText());
        int pay = Integer.parseInt(jtxtPay.getText());
        int bal = pay - tot;
        jtxtBal.setText(String.valueOf(bal));
    }//GEN-LAST:event_jtxtBalMouseEntered

    private void jtxtQnt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtQnt1MouseClicked
         
    }//GEN-LAST:event_jtxtQnt1MouseClicked

    private void jtxtQnt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtQnt1MouseReleased
        
    }//GEN-LAST:event_jtxtQnt1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jbtnCal;
    private javax.swing.JButton jbtnCal1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnUpdate1;
    private javax.swing.JTextField jtxtBal;
    private javax.swing.JTextField jtxtDose1;
    private javax.swing.JTextField jtxtExp1;
    private javax.swing.JTextField jtxtName1;
    private javax.swing.JTextField jtxtPay;
    private javax.swing.JTextField jtxtPrice1;
    private javax.swing.JTextField jtxtQnt1;
    private javax.swing.JTextField jtxtRef1;
    private javax.swing.JTextField jtxtTot1;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables
}
