/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy;

import Bill.Bill;
import Login.Home;
import Login.Login;

import pharminfo.pharminfo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel ;
import java.sql.DriverManager;
import java.sql.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;





/**
 *
 * @author HP
 */
public class pharmacy extends javax.swing.JFrame {

    
    

    /**
     * Creates new form pharmacy
     */
    public pharmacy() {
        initComponents();
        
            
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        
        }
            
        DisplayTable();
    }
    private void DisplayTable()
    { 
        
    
        
       try {
           String url = "jdbc:mysql://localhost:3306/pharmacy";
             Connection conn = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url,"root","Pharm@123");
            String sql= "select * from pharmm ";
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pharmacy.class.getName()).log(Level.SEVERE, null, ex);
    }   catch (SQLException ex) {
            Logger.getLogger(pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtNumberTablets = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtDailyDose = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtPharmID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnUpdate1 = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnview = new javax.swing.JButton();
        jtxtRef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Medicine Code:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jtxtName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Medicine Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Dose:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 220, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Quantity:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 220, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Price :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 220, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Issued Date:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtPossibleSideEffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPossibleSideEffectsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 220, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Expiry Date:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jtxtPharmID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtPharmID, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 220, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Medicine Code", "Dose(mg)", "Quantity", "Price", "Issued Date", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 1160, 170));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 100, 40));

        btnSave.setText("UPDATE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 100, 40));

        jbtnPatient.setText("SELL MEDICINE");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 120, 40));

        jbtnLogin.setText("BACK");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 100, 40));

        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 100, 40));

        jbtnUpdate1.setText("ADD");
        jbtnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 40));

        jbtnDoctor.setText("CANCEL");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 100, 40));

        jbtnview.setText("VIEW MEDICINE");
        jbtnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnviewActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 1150, 100));

        jtxtRef.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/sellMedicineBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNumberTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberTabletsActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
      Home iHome= new Home();
      iHome.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Pharmacy Management Systems",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0); }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
    if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to delete?","Pharmacy Management Systems",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }  
        String url = "jdbc:mysql://localhost:3306/pharmacy";
            Connection conn = null;
            
            
            
            
           try{
              String Medicine_Code=jtxtRef.getText();
            conn = DriverManager.getConnection(url,"root","Pharm@123");
            
            PreparedStatement ps=conn.prepareStatement("Delete from pharmm where Medicine_Code=?");
            ps.setString(1,Medicine_Code);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Deleted");
             DisplayTable();
            
           
            
            
           
            
           }catch (SQLException ex) {
            Logger.getLogger(pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
               
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
       Bill iBill = new Bill();
        iBill.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    private void jbtnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdate1ActionPerformed
       DefaultTableModel model1= (DefaultTableModel)jTable1.getModel();
       model1.addRow(new Object[]{
           
            
            jtxtName.getText(),
            jtxtRef.getText(),
            jtxtDose.getText(),
            jtxtNumberTablets.getText(),
            jtxtDailyDose.getText(),
            jtxtPossibleSideEffects.getText(),
            jtxtPharmID.getText(),
           
            });
    }//GEN-LAST:event_jbtnUpdate1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }  
        String url = "jdbc:mysql://localhost:3306/pharmacy";
            Connection conn = null;
            
            
            
           try{
                
            conn = DriverManager.getConnection(url,"root","Pharm@123");
            System.out.println("connection successful");
            String sql = "insert into pharmm values(?,?,?,?,?,?,?)";
            PreparedStatement ps=conn.prepareStatement(sql);
            
            ps.setString(1,jtxtName.getText());
            ps.setString(2,jtxtRef.getText());
            ps.setString(3,jtxtDose.getText());
            ps.setString(4,jtxtNumberTablets.getText());
            ps.setString(5,jtxtDailyDose.getText());
            ps.setString(6,jtxtPossibleSideEffects.getText());
            ps.setString(7,jtxtPharmID.getText());
           
            
           ps.executeUpdate();
             JOptionPane.showMessageDialog(this,"Saved");
             jtxtName.setText("");
        jtxtRef.setText("");
        jtxtDose.setText("");
        jtxtNumberTablets.setText("");
        jtxtDailyDose.setText("");
        jtxtPossibleSideEffects.setText("");
        jtxtPharmID.setText("");
             
            
           
        
        } catch (SQLException ex) {
            Logger.getLogger(pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jtxtPossibleSideEffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPossibleSideEffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPossibleSideEffectsActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i= jTable1.getSelectedRow();
        TableModel res=jTable1.getModel();
        jtxtName.setText(res.getValueAt(i,0).toString());
                jtxtRef.setText(res.getValueAt(i,1).toString());
                jtxtDose.setText(res.getValueAt(i,2).toString());
                jtxtNumberTablets.setText(res.getValueAt(i,3).toString());
                jtxtDailyDose.setText(res.getValueAt(i,4).toString());
                jtxtPossibleSideEffects.setText(res.getValueAt(i,5).toString());
                jtxtPharmID.setText(res.getValueAt(i,6).toString());
                
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
       
            
    }//GEN-LAST:event_jTable1MouseEntered

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
        jtxtName.setText("");
        jtxtRef.setText("");
        jtxtDose.setText("");
        jtxtNumberTablets.setText("");
        jtxtDailyDose.setText("");
        jtxtPossibleSideEffects.setText("");
        jtxtPharmID.setText("");
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnviewActionPerformed
        pharminfo ipharminfo = new pharminfo();
        ipharminfo.setVisible(true);
    }//GEN-LAST:event_jbtnviewActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new pharmacy().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnUpdate1;
    private javax.swing.JButton jbtnview;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPharmID;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextField jtxtRef;
    // End of variables declaration//GEN-END:variables

    

}